version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongochallenge
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: root-db
volumes:
  dbdata6: